# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingForm.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settingsForm(object):
    def setupUi(self, settingsForm):
        settingsForm.setObjectName("settingsForm")
        settingsForm.setEnabled(True)
        settingsForm.resize(494, 505)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        settingsForm.setFont(font)
        self.horizontalLayoutWidget = QtWidgets.QWidget(settingsForm)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 431, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonFont = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonFont.setObjectName("buttonFont")
        self.horizontalLayout.addWidget(self.buttonFont)
        self.buttonColorText = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonColorText.setObjectName("buttonColorText")
        self.horizontalLayout.addWidget(self.buttonColorText)
        self.messageTextEdit = QtWidgets.QTextEdit(settingsForm)
        self.messageTextEdit.setGeometry(QtCore.QRect(30, 60, 431, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageTextEdit.sizePolicy().hasHeightForWidth())
        self.messageTextEdit.setSizePolicy(sizePolicy)
        self.messageTextEdit.setMinimumSize(QtCore.QSize(300, 200))
        self.messageTextEdit.setMaximumSize(QtCore.QSize(1024, 768))
        self.messageTextEdit.setObjectName("messageTextEdit")
        self.layoutWidget = QtWidgets.QWidget(settingsForm)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 288, 431, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resetTodefaultButton = QtWidgets.QPushButton(self.layoutWidget)
        self.resetTodefaultButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.resetTodefaultButton.setObjectName("resetTodefaultButton")
        self.verticalLayout.addWidget(self.resetTodefaultButton)
        self.clearCounterButton = QtWidgets.QPushButton(self.layoutWidget)
        self.clearCounterButton.setObjectName("clearCounterButton")
        self.verticalLayout.addWidget(self.clearCounterButton)
        self.layoutWidget1 = QtWidgets.QWidget(settingsForm)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 350, 310, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTimeCountShowMsg = QtWidgets.QLabel(self.layoutWidget1)
        self.labelTimeCountShowMsg.setObjectName("labelTimeCountShowMsg")
        self.horizontalLayout_2.addWidget(self.labelTimeCountShowMsg)
        self.lineEditTimeCountShowMsg = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditTimeCountShowMsg.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEditTimeCountShowMsg.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditTimeCountShowMsg.setObjectName("lineEditTimeCountShowMsg")
        self.horizontalLayout_2.addWidget(self.lineEditTimeCountShowMsg)
        self.layoutWidget2 = QtWidgets.QWidget(settingsForm)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 470, 431, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonCancel = QtWidgets.QPushButton(self.layoutWidget2)
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout_3.addWidget(self.buttonCancel)
        self.buttonSaveSettings = QtWidgets.QPushButton(self.layoutWidget2)
        self.buttonSaveSettings.setObjectName("buttonSaveSettings")
        self.horizontalLayout_3.addWidget(self.buttonSaveSettings)
        self.layoutWidget_2 = QtWidgets.QWidget(settingsForm)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 380, 310, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelTimeRepeat = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelTimeRepeat.setObjectName("labelTimeRepeat")
        self.horizontalLayout_5.addWidget(self.labelTimeRepeat)
        self.lineEditTimeRepeat = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditTimeRepeat.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEditTimeRepeat.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditTimeRepeat.setObjectName("lineEditTimeRepeat")
        self.horizontalLayout_5.addWidget(self.lineEditTimeRepeat)
        self.layoutWidget_3 = QtWidgets.QWidget(settingsForm)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 440, 311, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelStartShowSince = QtWidgets.QLabel(self.layoutWidget_3)
        self.labelStartShowSince.setObjectName("labelStartShowSince")
        self.horizontalLayout_6.addWidget(self.labelStartShowSince)
        self.timeEditStartShowSince = QtWidgets.QTimeEdit(self.layoutWidget_3)
        self.timeEditStartShowSince.setEnabled(True)
        self.timeEditStartShowSince.setMinimumSize(QtCore.QSize(30, 0))
        self.timeEditStartShowSince.setMaximumSize(QtCore.QSize(50, 16777215))
        self.timeEditStartShowSince.setObjectName("timeEditStartShowSince")
        self.horizontalLayout_6.addWidget(self.timeEditStartShowSince)
        self.widget = QtWidgets.QWidget(settingsForm)
        self.widget.setGeometry(QtCore.QRect(30, 410, 311, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labeldontShowAfter = QtWidgets.QLabel(self.widget)
        self.labeldontShowAfter.setObjectName("labeldontShowAfter")
        self.horizontalLayout_4.addWidget(self.labeldontShowAfter)
        self.timeEditDontShowAfter = QtWidgets.QTimeEdit(self.widget)
        self.timeEditDontShowAfter.setMinimumSize(QtCore.QSize(30, 0))
        self.timeEditDontShowAfter.setMaximumSize(QtCore.QSize(50, 16777215))
        self.timeEditDontShowAfter.setObjectName("timeEditDontShowAfter")
        self.horizontalLayout_4.addWidget(self.timeEditDontShowAfter)
        self.horizontalLayoutWidget.raise_()
        self.messageTextEdit.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.timeEditDontShowAfter.raise_()
        self.labeldontShowAfter.raise_()
        self.labeldontShowAfter.raise_()
        self.timeEditDontShowAfter.raise_()
        self.layoutWidget_2.raise_()
        self.layoutWidget_3.raise_()

        self.retranslateUi(settingsForm)
        QtCore.QMetaObject.connectSlotsByName(settingsForm)

    def retranslateUi(self, settingsForm):
        _translate = QtCore.QCoreApplication.translate
        settingsForm.setWindowTitle(_translate("settingsForm", "Настройки"))
        self.buttonFont.setText(_translate("settingsForm", "Шрифт..."))
        self.buttonColorText.setText(_translate("settingsForm", "Цвет текста..."))
        self.messageTextEdit.setHtml(_translate("settingsForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.resetTodefaultButton.setText(_translate("settingsForm", "Восстановить настройки по-умолчанию"))
        self.clearCounterButton.setText(_translate("settingsForm", "Сбросить счетчик"))
        self.labelTimeCountShowMsg.setToolTip(_translate("settingsForm", "<html><head/><body><p>Время, в течении которого будет показваться напоминание. По умолчанию - 2 мин.</p></body></html>"))
        self.labelTimeCountShowMsg.setText(_translate("settingsForm", "Показывать напоминание (сек)                  "))
        self.lineEditTimeCountShowMsg.setToolTip(_translate("settingsForm", "<html><head/><body><p>Время, в течении которого будет показваться напоминание. По умолчанию - 2 мин.</p></body></html>"))
        self.buttonCancel.setText(_translate("settingsForm", "Отмена"))
        self.buttonSaveSettings.setText(_translate("settingsForm", "Сохранить настройки"))
        self.labelTimeRepeat.setToolTip(_translate("settingsForm", "<html><head/><body><p>Время, в течении которого будет показваться напоминание. По умолчанию - 2 мин.</p></body></html>"))
        self.labelTimeRepeat.setText(_translate("settingsForm", "Повторять напоминание каждые (мин)"))
        self.lineEditTimeRepeat.setToolTip(_translate("settingsForm", "<html><head/><body><p>Время, в течении которого будет показваться напоминание. По умолчанию - 2 мин.</p></body></html>"))
        self.labelStartShowSince.setText(_translate("settingsForm", "Показывать напоминание начиная с"))
        self.labeldontShowAfter.setText(_translate("settingsForm", "Не показывать напоминание после"))

